LTO_ENABLE = yes


OLED_ENABLE = no
DEFAULT_FOLDER = crkbd/rev1

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = yes
SRC += custom_keycodes.c
MOUSEKEY_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

